export const adverts = [
    [
        {image: 'kwality', isVideo: true, groupId: 1},
        {image: 'polo', isVideo: true, groupId: 4},
        {image: 'md1', isVideo: false, groupId: 5},
        {image: 'cor1', isVideo: true, groupId: 6},
        {image: 'cor2', isVideo: false, groupId: 6},
        {image: 'trix3', isVideo: false, groupId: 7},
        {image: 'jeep1', isVideo: false, groupId: 11},
        {image: 'jeep4', isVideo: false, groupId: 11},
        {image: 'jeep8', isVideo: false, groupId: 11},
    ], [
        {image: 'stayfree1', isVideo: true, groupId: 2},
        {image: 'vw1', isVideo: false, groupId: 4},
        {image: 'md2', isVideo: false, groupId: 5},
        {image: 'cor3', isVideo: false, groupId: 6},
        {image: 'happy1', isVideo: true, groupId: 8},
        {image: 'bbc1', isVideo: true, groupId: 9},
        {image: 'jeep2', isVideo: false, groupId: 11},
        {image: 'jeep5', isVideo: false, groupId: 11},
        {image: 'jeep9', isVideo: false, groupId: 11},
    ], [
        {image: 'stayfree2', isVideo: true, groupId: 2},
        {image: 'vw2', isVideo: false, groupId: 4},
        {image: 'md3', isVideo: false, groupId: 5},
        {image: 'cor4', isVideo: false, groupId: 6},
        {image: 'bbc2', isVideo: false, groupId: 9},
        {image: 'jeep3', isVideo: false, groupId: 11},
        {image: 'jeep7', isVideo: false, groupId: 11},
    ], [
        {image: 'facebook', isVideo: true, groupId: 3},
        {image: 'vw3', isVideo: false, groupId: 4},
        {image: 'md4', isVideo: false, groupId: 5},
        {image: 'trix1', isVideo: true, groupId: 7},
        {image: 'trix2', isVideo: false, groupId: 7},
        {image: 'covid1', isVideo: false, groupId: 10},
        {image: 'jeep6', isVideo: false, groupId: 11},
        {image: 'jeep10', isVideo: false, groupId: 11},
    ]
];
