export const adverts = [
    [
        {id: 1, image: 'kwality', isVideo: true, groupId: 1, ratio: "16:9", videoId: "V4dPeIPiJbM"},
        {id: 2, image: 'polo', isVideo: true, groupId: 4, ratio: "16:9", videoId: "4S-7FoZZQXQ"},
        {id: 3, image: 'md1', isVideo: false, groupId: 5, ratio: "9:16"},
        {id: 4, image: 'cor1', isVideo: true, groupId: 6, ratio: "16:9", videoId: "n47l41MalLk"},
        {id: 5, image: 'cor2', isVideo: false, groupId: 6, ratio: "16:9"},
        {id: 6, image: 'trix3', isVideo: false, groupId: 7, ratio: "9:16"},
        {id: 7, image: 'jeep1', isVideo: false, groupId: 11, ratio: "16:9"},
        {id: 8, image: 'jeep4', isVideo: false, groupId: 11, ratio: "16:9"},
        {id: 9, image: 'jeep8', isVideo: false, groupId: 11, ratio: "16:9"},
    ], [
        {id: 10, image: 'stayfree1', isVideo: true, groupId: 2, ratio: "16:9", videoId: "PcNKTwgZEEk"},
        {id: 11, image: 'vw1', isVideo: false, groupId: 4, ratio: "16:9"},
        {id: 12, image: 'md2', isVideo: false, groupId: 5, ratio: "9:16"},
        {id: 13, image: 'cor3', isVideo: false, groupId: 6, ratio: "9:16"},
        {id: 14, image: 'happy1', isVideo: true, groupId: 8, ratio: "16:9"},
        {id: 15, image: 'bbc1', isVideo: true, groupId: 9, ratio: "16:9", videoId: "Cc7ikWnHsU8"},
        {id: 16, image: 'jeep2', isVideo: false, groupId: 11, ratio: "16:9"},
        {id: 17, image: 'jeep5', isVideo: false, groupId: 11, ratio: "16:9"},
        {id: 18, image: 'jeep9', isVideo: false, groupId: 11, ratio: "16:9"},
    ], [
        {id: 19, image: 'stayfree2', isVideo: true, groupId: 12, ratio: "16:9", videoId: "khlgJP1sICE"},
        {id: 20, image: 'vw2', isVideo: false, groupId: 4, ratio: "16:9"},
        {id: 21, image: 'md3', isVideo: false, groupId: 5, ratio: "9:16"},
        {id: 22, image: 'cor4', isVideo: false, groupId: 6, ratio: "9:16"},
        {id: 23, image: 'bbc2', isVideo: false, groupId: 9, ratio: "9:16"},
        {id: 24, image: 'jeep3', isVideo: false, groupId: 11, ratio: "16:9"},
        {id: 25, image: 'jeep7', isVideo: false, groupId: 11, ratio: "9:16"},
    ], [
        {id: 26, image: 'facebook', isVideo: true, groupId: 3, ratio: "16:9", videoId: "HmMeUiZp-bE"},
        {id: 27, image: 'vw3', isVideo: false, groupId: 4, ratio: "16:9"},
        {id: 28, image: 'md4', isVideo: false, groupId: 5, ratio: "9:16"},
        {id: 29, image: 'trix1', isVideo: true, groupId: 7, ratio: "16:9", videoId: "AaRhMH9-Vj8"},
        {id: 30, image: 'trix2', isVideo: false, groupId: 7, ratio: "9:16"},
        {id: 31, image: 'covid1', isVideo: false, groupId: 10, ratio: "9:16"},
        {id: 32, image: 'jeep6', isVideo: false, groupId: 11, ratio: "16:9"},
        {id: 33, image: 'jeep10', isVideo: false, groupId: 11, ratio: "16:9"},
    ]
];
